version: '3'
services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    driver: bridge
